/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandDomainRouteImport } from './routes/brand.$domain'
import { Route as ApiSnapshotRouteImport } from './routes/api/snapshot'
import { Route as ApiScreenshotRouteImport } from './routes/api/screenshot'
import { Route as ApiScrapeRouteImport } from './routes/api/scrape'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as ApiMarkdownRouteImport } from './routes/api/markdown'
import { Route as ApiLinksRouteImport } from './routes/api/links'
import { Route as ApiItemsRouteImport } from './routes/api/items'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiBrandRouteImport } from './routes/api/brand'

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandDomainRoute = BrandDomainRouteImport.update({
  id: '/brand/$domain',
  path: '/brand/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapshotRoute = ApiSnapshotRouteImport.update({
  id: '/api/snapshot',
  path: '/api/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotRoute = ApiScreenshotRouteImport.update({
  id: '/api/screenshot',
  path: '/api/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeRoute = ApiScrapeRouteImport.update({
  id: '/api/scrape',
  path: '/api/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarkdownRoute = ApiMarkdownRouteImport.update({
  id: '/api/markdown',
  path: '/api/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksRoute = ApiLinksRouteImport.update({
  id: '/api/links',
  path: '/api/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsRoute = ApiItemsRouteImport.update({
  id: '/api/items',
  path: '/api/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandRoute = ApiBrandRouteImport.update({
  id: '/api/brand',
  path: '/api/brand',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/api/brand': typeof ApiBrandRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/files': typeof ApiFilesRoute
  '/api/items': typeof ApiItemsRoute
  '/api/links': typeof ApiLinksRoute
  '/api/markdown': typeof ApiMarkdownRoute
  '/api/pdf': typeof ApiPdfRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/brand/$domain': typeof BrandDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/api/brand': typeof ApiBrandRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/files': typeof ApiFilesRoute
  '/api/items': typeof ApiItemsRoute
  '/api/links': typeof ApiLinksRoute
  '/api/markdown': typeof ApiMarkdownRoute
  '/api/pdf': typeof ApiPdfRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/brand/$domain': typeof BrandDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/api/brand': typeof ApiBrandRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/files': typeof ApiFilesRoute
  '/api/items': typeof ApiItemsRoute
  '/api/links': typeof ApiLinksRoute
  '/api/markdown': typeof ApiMarkdownRoute
  '/api/pdf': typeof ApiPdfRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/brand/$domain': typeof BrandDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/api/brand'
    | '/api/extract'
    | '/api/feed'
    | '/api/files'
    | '/api/items'
    | '/api/links'
    | '/api/markdown'
    | '/api/pdf'
    | '/api/scrape'
    | '/api/screenshot'
    | '/api/snapshot'
    | '/brand/$domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/api/brand'
    | '/api/extract'
    | '/api/feed'
    | '/api/files'
    | '/api/items'
    | '/api/links'
    | '/api/markdown'
    | '/api/pdf'
    | '/api/scrape'
    | '/api/screenshot'
    | '/api/snapshot'
    | '/brand/$domain'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/api/brand'
    | '/api/extract'
    | '/api/feed'
    | '/api/files'
    | '/api/items'
    | '/api/links'
    | '/api/markdown'
    | '/api/pdf'
    | '/api/scrape'
    | '/api/screenshot'
    | '/api/snapshot'
    | '/brand/$domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  ApiBrandRoute: typeof ApiBrandRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiItemsRoute: typeof ApiItemsRoute
  ApiLinksRoute: typeof ApiLinksRoute
  ApiMarkdownRoute: typeof ApiMarkdownRoute
  ApiPdfRoute: typeof ApiPdfRoute
  ApiScrapeRoute: typeof ApiScrapeRoute
  ApiScreenshotRoute: typeof ApiScreenshotRoute
  ApiSnapshotRoute: typeof ApiSnapshotRoute
  BrandDomainRoute: typeof BrandDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$domain': {
      id: '/brand/$domain'
      path: '/brand/$domain'
      fullPath: '/brand/$domain'
      preLoaderRoute: typeof BrandDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshot': {
      id: '/api/snapshot'
      path: '/api/snapshot'
      fullPath: '/api/snapshot'
      preLoaderRoute: typeof ApiSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshot': {
      id: '/api/screenshot'
      path: '/api/screenshot'
      fullPath: '/api/screenshot'
      preLoaderRoute: typeof ApiScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape': {
      id: '/api/scrape'
      path: '/api/scrape'
      fullPath: '/api/scrape'
      preLoaderRoute: typeof ApiScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markdown': {
      id: '/api/markdown'
      path: '/api/markdown'
      fullPath: '/api/markdown'
      preLoaderRoute: typeof ApiMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links': {
      id: '/api/links'
      path: '/api/links'
      fullPath: '/api/links'
      preLoaderRoute: typeof ApiLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items': {
      id: '/api/items'
      path: '/api/items'
      fullPath: '/api/items'
      preLoaderRoute: typeof ApiItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand': {
      id: '/api/brand'
      path: '/api/brand'
      fullPath: '/api/brand'
      preLoaderRoute: typeof ApiBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  ApiBrandRoute: ApiBrandRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiItemsRoute: ApiItemsRoute,
  ApiLinksRoute: ApiLinksRoute,
  ApiMarkdownRoute: ApiMarkdownRoute,
  ApiPdfRoute: ApiPdfRoute,
  ApiScrapeRoute: ApiScrapeRoute,
  ApiScreenshotRoute: ApiScreenshotRoute,
  ApiSnapshotRoute: ApiSnapshotRoute,
  BrandDomainRoute: BrandDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
